version: "3"
services:
  dev:
    container_name: 'mshots-dev'
    user: "${UID}:${GID}"
    environment:
        - UID
        - USER
        - MSHOTS_MEMCACHE_HOST=memcached
    build:
      context: .
      args:
        - UID
        - USER
    ports:
      - '7777:7777'
      - '8000:8000'
    volumes:
      - ./:/opt/mshots/

  memcached:
    container_name: memcached
    image: memcached:latest
    expose:
      - '11211'
