version: "3"
services:
  mshots:
    container_name: 'mshots'
    environment:
        - USER=www-data
        - UID=33
        - MSHOTS_MEMCACHE_HOST=memcached
    build:
      context: .
    ports:
      - '8000:8000'

  memcached:
    container_name: memcached
    image: memcached:latest
    expose:
      - '11211'
